"""Add IxHeadTitle Index

Revision ID: 008d3aebcf62
Revises: 651246466888
Create Date: 2025-05-07 09:02:06.554352

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '008d3aebcf62'
down_revision = '651246466888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ix_head_title_seccode_date', 'ix_head_title', ['securities_code', 'reporting_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ix_head_title_seccode_date', table_name='ix_head_title')
    # ### end Alembic commands ###
