"""JpxStockInfo add Index

Revision ID: 00cc28b04623
Revises: 2a099f100f27
Create Date: 2025-01-29 22:31:08.300538

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '00cc28b04623'
down_revision = '2a099f100f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('jpx_stock_info_industry_17_code', 'jpx_stock_info', ['industry_17_code'], unique=False)
    op.create_index('jpx_stock_info_industry_33_code', 'jpx_stock_info', ['industry_33_code'], unique=False)
    op.create_index('jpx_stock_info_market_or_type', 'jpx_stock_info', ['market_or_type'], unique=False)
    op.create_index('jpx_stock_info_scale_code', 'jpx_stock_info', ['scale_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('jpx_stock_info_scale_code', table_name='jpx_stock_info')
    op.drop_index('jpx_stock_info_market_or_type', table_name='jpx_stock_info')
    op.drop_index('jpx_stock_info_industry_33_code', table_name='jpx_stock_info')
    op.drop_index('jpx_stock_info_industry_17_code', table_name='jpx_stock_info')
    # ### end Alembic commands ###
