"""Add BaseTable Change

Revision ID: 0963623045af
Revises: 8ce94a49f041
Create Date: 2025-06-13 11:48:30.884173

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0963623045af'
down_revision = '8ce94a49f041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
