"""stock_wiki table add column by kent

Revision ID: 0a3884e17235
Revises: d5847526e014
Create Date: 2025-02-14 00:03:26.165786

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0a3884e17235'
down_revision = 'd5847526e014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_wiki', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_wiki', 'name')
    # ### end Alembic commands ###
