"""insertDate UpdateDate reset

Revision ID: 0e391d752506
Revises: e5011577b6b6
Create Date: 2025-05-13 11:19:11.971013

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0e391d752506'
down_revision = 'e5011577b6b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
