"""Change IcHeadTitleSummary Base Change

Revision ID: 0e8fc85dff6e
Revises: 0963623045af
Create Date: 2025-06-13 11:50:14.938123

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0e8fc85dff6e'
down_revision = '0963623045af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ix_head_title_summary_item_key_key', 'ix_head_title_summary', type_='unique')
    op.drop_column('ix_head_title_summary', 'id')
    op.drop_column('ix_head_title_summary', 'item_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ix_head_title_summary', sa.Column('item_key', sa.VARCHAR(length=36), autoincrement=False, nullable=True, comment='ItemKey'))
    op.add_column('ix_head_title_summary', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='ID'))
    op.create_unique_constraint('ix_head_title_summary_item_key_key', 'ix_head_title_summary', ['item_key'])
    # ### end Alembic commands ###
