"""ix_head_title add index is_active&is_generate

Revision ID: 16a9353c24ee
Revises: 26e08fae91ce
Create Date: 2024-11-10 23:58:22.256590

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '16a9353c24ee'
down_revision = '26e08fae91ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ix_head_title_is_active', 'ix_head_title', ['is_active'], unique=False)
    op.create_index('idx_ix_head_title_is_generated', 'ix_head_title', ['is_generated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ix_head_title_is_generated', table_name='ix_head_title')
    op.drop_index('idx_ix_head_title_is_active', table_name='ix_head_title')
    # ### end Alembic commands ###
