"""JpxStockInfo Add Column

Revision ID: 17cbe02c373e
Revises: 58b7d3bdef5f
Create Date: 2025-01-29 21:23:09.136938

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '17cbe02c373e'
down_revision = '58b7d3bdef5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jpx_stock_info', sa.Column('input_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jpx_stock_info', 'input_date')
    # ### end Alembic commands ###
