"""ix delete

Revision ID: 1eb110559f01
Revises: 87db8c3d4b6c
Create Date: 2024-10-22 23:04:31.532932

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1eb110559f01'
down_revision = '87db8c3d4b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockbase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockbase',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stockbase_pkey')
    )
    # ### end Alembic commands ###
