"""ix_head_title add index report_type

Revision ID: 26e08fae91ce
Revises: 954d7d976382
Create Date: 2024-11-10 23:53:09.068728

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '26e08fae91ce'
down_revision = '954d7d976382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ix_head_title_report_type', 'ix_head_title', ['report_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ix_head_title_report_type', table_name='ix_head_title')
    # ### end Alembic commands ###
