"""JpxStockInfo input_date change max_lenght

Revision ID: 2a099f100f27
Revises: 59da0619c31f
Create Date: 2025-01-29 21:57:11.520130

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2a099f100f27'
down_revision = '59da0619c31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jpx_stock_info', 'code',
               existing_type=sa.VARCHAR(length=4),
               type_=sqlmodel.sql.sqltypes.AutoString(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jpx_stock_info', 'code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=5),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    # ### end Alembic commands ###
