"""stock_wiki table url description delete max_lenght by kent

Revision ID: 31d72a3139dc
Revises: d7bc55f2341a
Create Date: 2025-02-14 21:30:56.052516

"""

# revision identifiers, used by Alembic.
revision = "31d72a3139dc"
down_revision = "d7bc55f2341a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
