"""Ix init

Revision ID: 516043f4c7b6
Revises: 1a31ce608336
Create Date: 2024-11-07 01:20:06.982982

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '516043f4c7b6'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ix_file_path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('xbrl_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key'),
    sa.UniqueConstraint('xbrl_id')
    )
    op.create_table('ix_stock_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('payout_ratio', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('roe', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('roa', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('op_margin', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cf_operating', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cf_investing', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cf_financing', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cash_end', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_table('ix_head_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('securities_code', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('document_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('reporting_date', sa.Date(), nullable=False),
    sa.Column('current_period', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xbrl_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('listed_market', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('market_section', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_bs', sa.Boolean(), nullable=True),
    sa.Column('is_pl', sa.Boolean(), nullable=True),
    sa.Column('is_cf', sa.Boolean(), nullable=True),
    sa.Column('is_ci', sa.Boolean(), nullable=True),
    sa.Column('is_sce', sa.Boolean(), nullable=True),
    sa.Column('is_sfp', sa.Boolean(), nullable=True),
    sa.Column('fiscal_year_end', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_dividend_revision', sa.Boolean(), nullable=True),
    sa.Column('dividend_increase_rate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_earnings_forecast_revision', sa.Boolean(), nullable=True),
    sa.Column('forecast_ordinary_income_growth_rate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['xbrl_id'], ['ix_file_path.xbrl_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key'),
    sa.UniqueConstraint('xbrl_id')
    )
    op.create_table('ix_source_file',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xbrl_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['xbrl_id'], ['ix_head_title.xbrl_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_index('idx_ix_source_file_id', 'ix_source_file', ['id'], unique=False)
    op.create_table('ix_calculation_arc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_arcrole', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xlink_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xbrl_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('attr_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_order', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('xlink_weight', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_table('ix_calculation_loc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_schema', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xbrl_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('attr_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_href', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_table('ix_definition_arc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_arcrole', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_to', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('xlink_from', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('xbrl_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('attr_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_order', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('xlink_weight', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key'),
    sa.UniqueConstraint('xbrl_id', 'source_file_id', 'xlink_from', 'xlink_to', 'xlink_arcrole', 'attr_value', name='ix_definition_arc_uc')
    )
    op.create_index('idx_ix_definition_arc_attr_value', 'ix_definition_arc', ['attr_value'], unique=False)
    op.create_index('idx_ix_definition_arc_attr_value_xlink_from', 'ix_definition_arc', ['attr_value', 'xlink_from'], unique=False)
    op.create_index('idx_ix_definition_arc_attr_value_xlink_to', 'ix_definition_arc', ['attr_value', 'xlink_to'], unique=False)
    op.create_index('idx_ix_definition_arc_source_file_id', 'ix_definition_arc', ['source_file_id'], unique=False)
    op.create_index('idx_ix_definition_arc_source_file_id_attr_value', 'ix_definition_arc', ['source_file_id', 'attr_value'], unique=False)
    op.create_index('idx_ix_definition_arc_xbrl_id', 'ix_definition_arc', ['xbrl_id'], unique=False)
    op.create_index('idx_ix_definition_arc_xlink_arcrole', 'ix_definition_arc', ['xlink_arcrole'], unique=False)
    op.create_index('idx_ix_definition_arc_xlink_from', 'ix_definition_arc', ['xlink_from'], unique=False)
    op.create_index('idx_ix_definition_arc_xlink_order', 'ix_definition_arc', ['xlink_order'], unique=False)
    op.create_index('idx_ix_definition_arc_xlink_to', 'ix_definition_arc', ['xlink_to'], unique=False)
    op.create_table('ix_definition_loc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_schema', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xbrl_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('attr_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_href', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key'),
    sa.UniqueConstraint('xbrl_id', 'source_file_id', 'xlink_label', 'xlink_href', 'attr_value', name='ix_definition_loc_uc')
    )
    op.create_index('idx_ix_definition_loc_attr_value', 'ix_definition_loc', ['attr_value'], unique=False)
    op.create_index('idx_ix_definition_loc_attr_value_xlink_label', 'ix_definition_loc', ['attr_value', 'xlink_label'], unique=False)
    op.create_index('idx_ix_definition_loc_source_file_id', 'ix_definition_loc', ['source_file_id'], unique=False)
    op.create_index('idx_ix_definition_loc_xbrl_id', 'ix_definition_loc', ['xbrl_id'], unique=False)
    op.create_index('idx_ix_definition_loc_xlink_href', 'ix_definition_loc', ['xlink_href'], unique=False)
    op.create_index('idx_ix_definition_loc_xlink_label', 'ix_definition_loc', ['xlink_label'], unique=False)
    op.create_table('ix_label_arc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_arcrole', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xlink_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key'),
    sa.UniqueConstraint('xlink_arcrole', 'xlink_from', 'xlink_to', 'source_file_id', name='ix_label_arc_uc')
    )
    op.create_index('idx_ix_label_arc_source_file_id', 'ix_label_arc', ['source_file_id'], unique=False)
    op.create_index('idx_ix_label_arc_source_file_id_xlink_from', 'ix_label_arc', ['source_file_id', 'xlink_from'], unique=False)
    op.create_index('idx_ix_label_arc_source_file_id_xlink_to', 'ix_label_arc', ['source_file_id', 'xlink_to'], unique=False)
    op.create_table('ix_label_loc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_schema', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_href', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xlink_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key'),
    sa.UniqueConstraint('xlink_href', 'xlink_label', 'source_file_id', name='ix_label_loc_uc')
    )
    op.create_index('idx_ix_label_loc_source_file_id_xlink_label', 'ix_label_loc', ['source_file_id', 'xlink_label'], unique=False)
    op.create_index('idx_ix_label_loc_xlink_href', 'ix_label_loc', ['xlink_href'], unique=False)
    op.create_index('idx_ix_label_loc_xlink_label', 'ix_label_loc', ['xlink_label'], unique=False)
    op.create_table('ix_label_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xlink_role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xml_lang', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key'),
    sa.UniqueConstraint('xlink_label', 'source_file_id', name='ix_label_value_uc')
    )
    op.create_index('idx_ix_label_value_source_file_id', 'ix_label_value', ['source_file_id'], unique=False)
    op.create_index('idx_ix_label_value_xlink_label', 'ix_label_value', ['xlink_label'], unique=False)
    op.create_index('idx_ix_label_value_xlink_role', 'ix_label_value', ['xlink_role'], unique=False)
    op.create_table('ix_non_fraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('xbrl_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decimals', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scale', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('sign', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('unit_ref', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xsi_nil', sa.Boolean(), nullable=True),
    sa.Column('numeric', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('ixbrl_role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('xbrl_type', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('display_numeric', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_scale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_index('idx_ix_non_fraction_context', 'ix_non_fraction', ['context'], unique=False)
    op.create_index('idx_ix_non_fraction_name', 'ix_non_fraction', ['name'], unique=False)
    op.create_index('idx_ix_non_fraction_xbrl_id', 'ix_non_fraction', ['xbrl_id'], unique=False)
    op.create_index('idx_ix_non_fraction_xbrl_type', 'ix_non_fraction', ['xbrl_type'], unique=False)
    op.create_table('ix_non_numeric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('xbrl_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('xsi_nil', sa.Boolean(), nullable=True),
    sa.Column('escape', sa.Boolean(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('ixbrl_role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('xbrl_type', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_index('idx_ix_non_numeric_context', 'ix_non_numeric', ['context'], unique=False)
    op.create_index('idx_ix_non_numeric_name', 'ix_non_numeric', ['name'], unique=False)
    op.create_index('idx_ix_non_numeric_xbrl_id', 'ix_non_numeric', ['xbrl_id'], unique=False)
    op.create_index('idx_ix_non_numeric_xbrl_type', 'ix_non_numeric', ['xbrl_type'], unique=False)
    op.create_table('ix_presentation_arc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_arcrole', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xlink_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xbrl_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('attr_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_order', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('xlink_weight', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_table('ix_presentation_loc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_schema', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xbrl_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('attr_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_href', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_table('ix_qualitative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('currentId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('parentId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('xbrl_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currentId'),
    sa.UniqueConstraint('item_key')
    )
    op.create_table('ix_schema_linkbase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('xlink_arcrole', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_href', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('xbrl_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('xbrl_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('href_source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['href_source_file_id'], ['ix_source_file.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_index('idx_ix_schema_linkbase_href_source_file_id', 'ix_schema_linkbase', ['href_source_file_id'], unique=False)
    op.create_index('idx_ix_schema_linkbase_xbrl_id', 'ix_schema_linkbase', ['xbrl_id'], unique=False)
    op.create_index('idx_ix_schema_linkbase_xbrl_id_xlink_role', 'ix_schema_linkbase', ['xbrl_id', 'xlink_role'], unique=False)
    op.create_index('idx_ix_schema_linkbase_xbrl_type', 'ix_schema_linkbase', ['xbrl_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ix_schema_linkbase_xbrl_type', table_name='ix_schema_linkbase')
    op.drop_index('idx_ix_schema_linkbase_xbrl_id_xlink_role', table_name='ix_schema_linkbase')
    op.drop_index('idx_ix_schema_linkbase_xbrl_id', table_name='ix_schema_linkbase')
    op.drop_index('idx_ix_schema_linkbase_href_source_file_id', table_name='ix_schema_linkbase')
    op.drop_table('ix_schema_linkbase')
    op.drop_table('ix_qualitative')
    op.drop_table('ix_presentation_loc')
    op.drop_table('ix_presentation_arc')
    op.drop_index('idx_ix_non_numeric_xbrl_type', table_name='ix_non_numeric')
    op.drop_index('idx_ix_non_numeric_xbrl_id', table_name='ix_non_numeric')
    op.drop_index('idx_ix_non_numeric_name', table_name='ix_non_numeric')
    op.drop_index('idx_ix_non_numeric_context', table_name='ix_non_numeric')
    op.drop_table('ix_non_numeric')
    op.drop_index('idx_ix_non_fraction_xbrl_type', table_name='ix_non_fraction')
    op.drop_index('idx_ix_non_fraction_xbrl_id', table_name='ix_non_fraction')
    op.drop_index('idx_ix_non_fraction_name', table_name='ix_non_fraction')
    op.drop_index('idx_ix_non_fraction_context', table_name='ix_non_fraction')
    op.drop_table('ix_non_fraction')
    op.drop_index('idx_ix_label_value_xlink_role', table_name='ix_label_value')
    op.drop_index('idx_ix_label_value_xlink_label', table_name='ix_label_value')
    op.drop_index('idx_ix_label_value_source_file_id', table_name='ix_label_value')
    op.drop_table('ix_label_value')
    op.drop_index('idx_ix_label_loc_xlink_label', table_name='ix_label_loc')
    op.drop_index('idx_ix_label_loc_xlink_href', table_name='ix_label_loc')
    op.drop_index('idx_ix_label_loc_source_file_id_xlink_label', table_name='ix_label_loc')
    op.drop_table('ix_label_loc')
    op.drop_index('idx_ix_label_arc_source_file_id_xlink_to', table_name='ix_label_arc')
    op.drop_index('idx_ix_label_arc_source_file_id_xlink_from', table_name='ix_label_arc')
    op.drop_index('idx_ix_label_arc_source_file_id', table_name='ix_label_arc')
    op.drop_table('ix_label_arc')
    op.drop_index('idx_ix_definition_loc_xlink_label', table_name='ix_definition_loc')
    op.drop_index('idx_ix_definition_loc_xlink_href', table_name='ix_definition_loc')
    op.drop_index('idx_ix_definition_loc_xbrl_id', table_name='ix_definition_loc')
    op.drop_index('idx_ix_definition_loc_source_file_id', table_name='ix_definition_loc')
    op.drop_index('idx_ix_definition_loc_attr_value_xlink_label', table_name='ix_definition_loc')
    op.drop_index('idx_ix_definition_loc_attr_value', table_name='ix_definition_loc')
    op.drop_table('ix_definition_loc')
    op.drop_index('idx_ix_definition_arc_xlink_to', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_xlink_order', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_xlink_from', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_xlink_arcrole', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_xbrl_id', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_source_file_id_attr_value', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_source_file_id', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_attr_value_xlink_to', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_attr_value_xlink_from', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_attr_value', table_name='ix_definition_arc')
    op.drop_table('ix_definition_arc')
    op.drop_table('ix_calculation_loc')
    op.drop_table('ix_calculation_arc')
    op.drop_index('idx_ix_source_file_id', table_name='ix_source_file')
    op.drop_table('ix_source_file')
    op.drop_table('ix_head_title')
    op.drop_table('ix_stock_infos')
    op.drop_table('ix_file_path')
    # ### end Alembic commands ###
