"""JpxStockInfo Table delete max_length from int field

Revision ID: 58b7d3bdef5f
Revises: f99da43d202e
Create Date: 2025-01-29 06:06:01.412819

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '58b7d3bdef5f'
down_revision = 'f99da43d202e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
