"""JpxStockInfo input_date change str

Revision ID: 59da0619c31f
Revises: 17cbe02c373e
Create Date: 2025-01-29 21:47:51.838031

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '59da0619c31f'
down_revision = '17cbe02c373e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jpx_stock_info', 'input_date',
               existing_type=sa.DATE(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jpx_stock_info', 'input_date',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=8),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
