"""stock_wiki table url description chenge Text by kent

Revision ID: 651246466888
Revises: 31d72a3139dc
Create Date: 2025-02-14 21:35:28.429155

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "651246466888"
down_revision = "31d72a3139dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_wiki",
        "description",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_wiki",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
