"""insertDate updateDate Change local

Revision ID: 697663c89a61
Revises: 008d3aebcf62
Create Date: 2025-05-12 22:53:55.518413

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '697663c89a61'
down_revision = '008d3aebcf62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
