"""add head culumn

Revision ID: 738e6bfeec43
Revises: e4547e321d6c
Create Date: 2024-11-25 22:28:26.553903

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '738e6bfeec43'
down_revision = 'e4547e321d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ix_head_title', sa.Column('specific_business', sa.Boolean(), nullable=True))
    op.create_index('idx_ix_head_specific_business', 'ix_head_title', ['specific_business'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ix_head_specific_business', table_name='ix_head_title')
    op.drop_column('ix_head_title', 'specific_business')
    # ### end Alembic commands ###
