"""ix Index Change

Revision ID: 73fc5daee05a
Revises: 36fbc50fe21c
Create Date: 2024-10-23 20:49:28.638926

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "73fc5daee05a"
down_revision = "36fbc50fe21c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ix_stock_infos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("insert_date", sa.DateTime(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "payout_ratio", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("roe", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("roa", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "op_margin", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "cf_operating", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "cf_investing", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "cf_financing", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "cash_end", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ix_definition_loc_xlink_href",
        "ix_definition_loc",
        ["xlink_href"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ix_definition_loc_xlink_href", table_name="ix_definition_loc")
    op.drop_table("ix_stock_infos")
    # ### end Alembic commands ###
