"""insertDate UpdateDate ZoneInfo

Revision ID: 77213b4a1eb7
Revises: 0e391d752506
Create Date: 2025-05-13 11:25:11.718424

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '77213b4a1eb7'
down_revision = '0e391d752506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
