"""Add DailyStockPrice Table

Revision ID: 7e3713854ef7
Revises: bb530736da29
Create Date: 2025-05-23 13:28:36.970479

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7e3713854ef7'
down_revision = 'bb530736da29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stock_price',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('days', sa.Date(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('high', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('low', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('close', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('adjusted_close', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'days', name='uq_daily_stock_price_code_days')
    )
    op.create_index('daily_stock_price_code', 'daily_stock_price', ['code'], unique=False)
    op.create_index('daily_stock_price_days', 'daily_stock_price', ['days'], unique=False)
    op.create_index(op.f('ix_daily_stock_price_code'), 'daily_stock_price', ['code'], unique=False)
    op.create_index(op.f('ix_daily_stock_price_days'), 'daily_stock_price', ['days'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_stock_price_days'), table_name='daily_stock_price')
    op.drop_index(op.f('ix_daily_stock_price_code'), table_name='daily_stock_price')
    op.drop_index('daily_stock_price_days', table_name='daily_stock_price')
    op.drop_index('daily_stock_price_code', table_name='daily_stock_price')
    op.drop_table('daily_stock_price')
    # ### end Alembic commands ###
