"""JpxStockInfoBase timezone change

Revision ID: 7e57ccced6ae
Revises: 77213b4a1eb7
Create Date: 2025-05-14 12:10:00.431645

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7e57ccced6ae'
down_revision = '77213b4a1eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
