"""add index

Revision ID: 86a6fe74191e
Revises: 738e6bfeec43
Create Date: 2024-11-26 20:39:54.896679

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '86a6fe74191e'
down_revision = '738e6bfeec43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ix_label_arc_xlink_from', 'ix_label_arc', ['xlink_from'], unique=False)
    op.create_index('idx_ix_label_arc_xlink_to', 'ix_label_arc', ['xlink_to'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ix_label_arc_xlink_to', table_name='ix_label_arc')
    op.drop_index('idx_ix_label_arc_xlink_from', table_name='ix_label_arc')
    # ### end Alembic commands ###
