"""ix init

Revision ID: 87db8c3d4b6c
Revises: 1a31ce608336
Create Date: 2024-10-22 23:02:38.079630

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '87db8c3d4b6c'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockbase',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockbase')
    # ### end Alembic commands ###
