"""Add IxHeadTitleSummary Table

Revision ID: 8ce94a49f041
Revises: 7e3713854ef7
Create Date: 2025-06-12 22:58:29.336943

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8ce94a49f041'
down_revision = '7e3713854ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ix_head_title_summary',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('head_item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('head_item_key'),
    sa.UniqueConstraint('item_key')
    )
    op.create_index('ix_head_title_summary_head_item_key', 'ix_head_title_summary', ['head_item_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_head_title_summary_head_item_key', table_name='ix_head_title_summary')
    op.drop_table('ix_head_title_summary')
    # ### end Alembic commands ###
