"""model change

Revision ID: 90a05bd911ac
Revises: 7e57ccced6ae
Create Date: 2025-05-17 13:49:40.447127

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '90a05bd911ac'
down_revision = '7e57ccced6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
