"""ix_head_title add index

Revision ID: 954d7d976382
Revises: e65d918ff7d3
Create Date: 2024-11-10 23:47:48.889998

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '954d7d976382'
down_revision = 'e65d918ff7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ix_head_title_item_key', 'ix_head_title', ['item_key'], unique=False)
    op.create_index('idx_ix_head_title_reporting_date', 'ix_head_title', ['reporting_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ix_head_title_reporting_date', table_name='ix_head_title')
    op.drop_index('idx_ix_head_title_item_key', table_name='ix_head_title')
    # ### end Alembic commands ###
