"""Delete table

Revision ID: 95e6436b916f
Revises: ea17349247ae
Create Date: 2025-01-29 05:24:43.214689

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95e6436b916f'
down_revision = 'ea17349247ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ix_stock_infos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ix_stock_infos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('item_key', sa.VARCHAR(length=36), autoincrement=False, nullable=True, comment='ItemKey'),
    sa.Column('insert_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='作成日時'),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新日時'),
    sa.Column('code', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payout_ratio', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('roe', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('roa', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('op_margin', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cf_operating', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cf_investing', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cf_financing', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cash_end', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ix_stock_infos_pkey'),
    sa.UniqueConstraint('item_key', name='ix_stock_infos_item_key_key')
    )
    # ### end Alembic commands ###
