"""ix init2

Revision ID: 9be16999579f
Revises: cb3feabf2460
Create Date: 2024-10-30 19:19:31.020630

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9be16999579f'
down_revision = 'cb3feabf2460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ix_calculation_arc', ['item_key'])
    op.create_unique_constraint(None, 'ix_calculation_loc', ['item_key'])
    op.create_unique_constraint(None, 'ix_definition_arc', ['item_key'])
    op.create_unique_constraint(None, 'ix_definition_loc', ['item_key'])
    op.create_unique_constraint(None, 'ix_file_path', ['item_key'])
    op.create_unique_constraint(None, 'ix_head_title', ['item_key'])
    op.create_unique_constraint(None, 'ix_label_arc', ['item_key'])
    op.create_unique_constraint(None, 'ix_label_loc', ['item_key'])
    op.create_unique_constraint(None, 'ix_label_value', ['item_key'])
    op.create_unique_constraint(None, 'ix_non_fraction', ['item_key'])
    op.create_unique_constraint(None, 'ix_non_numeric', ['item_key'])
    op.create_unique_constraint(None, 'ix_presentation_arc', ['item_key'])
    op.create_unique_constraint(None, 'ix_presentation_loc', ['item_key'])
    op.create_unique_constraint(None, 'ix_qualitative', ['item_key'])
    op.create_unique_constraint(None, 'ix_schema_linkbase', ['item_key'])
    op.create_unique_constraint(None, 'ix_source_file', ['item_key'])
    op.create_unique_constraint(None, 'ix_stock_infos', ['item_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ix_stock_infos', type_='unique')
    op.drop_constraint(None, 'ix_source_file', type_='unique')
    op.drop_constraint(None, 'ix_schema_linkbase', type_='unique')
    op.drop_constraint(None, 'ix_qualitative', type_='unique')
    op.drop_constraint(None, 'ix_presentation_loc', type_='unique')
    op.drop_constraint(None, 'ix_presentation_arc', type_='unique')
    op.drop_constraint(None, 'ix_non_numeric', type_='unique')
    op.drop_constraint(None, 'ix_non_fraction', type_='unique')
    op.drop_constraint(None, 'ix_label_value', type_='unique')
    op.drop_constraint(None, 'ix_label_loc', type_='unique')
    op.drop_constraint(None, 'ix_label_arc', type_='unique')
    op.drop_constraint(None, 'ix_head_title', type_='unique')
    op.drop_constraint(None, 'ix_file_path', type_='unique')
    op.drop_constraint(None, 'ix_definition_loc', type_='unique')
    op.drop_constraint(None, 'ix_definition_arc', type_='unique')
    op.drop_constraint(None, 'ix_calculation_loc', type_='unique')
    op.drop_constraint(None, 'ix_calculation_arc', type_='unique')
    # ### end Alembic commands ###
