"""Rename StockInfo table

Revision ID: afb31e2caaaa
Revises: 95e6436b916f
Create Date: 2025-01-29 05:25:37.686302

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'afb31e2caaaa'
down_revision = '95e6436b916f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jpx_stock_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('market_or_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('industry_33_code', sa.Integer(), nullable=True),
    sa.Column('industry_33_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('industry_17_code', sa.Integer(), nullable=True),
    sa.Column('industry_17_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('scale_code', sa.Integer(), nullable=True),
    sa.Column('scale_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stock_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('insert_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='作成日時'),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新日時'),
    sa.Column('code', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('market_or_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('industry_33_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('industry_33_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('industry_17_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('industry_17_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('scale_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scale_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stock_info_pkey')
    )
    op.drop_table('jpx_stock_info')
    # ### end Alembic commands ###
