"""Rename StockInfo table add code field is unique

Revision ID: b40af2713e41
Revises: afb31e2caaaa
Create Date: 2025-01-29 05:36:12.165968

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b40af2713e41'
down_revision = 'afb31e2caaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'jpx_stock_info', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jpx_stock_info', type_='unique')
    # ### end Alembic commands ###
