"""Ix Table Init

Revision ID: bb530736da29
Revises: 1a31ce608336
Create Date: 2025-05-18 06:37:43.270766

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bb530736da29'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ix_file_path',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('head_item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False, comment='HeadItemKey'),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='パス'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('head_item_key'),
    sa.UniqueConstraint('item_key')
    )
    op.create_table('jpx_stock_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('input_date', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('market_or_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('industry_33_code', sa.Integer(), nullable=True),
    sa.Column('industry_33_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('industry_17_code', sa.Integer(), nullable=True),
    sa.Column('industry_17_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('scale_code', sa.Integer(), nullable=True),
    sa.Column('scale_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('jpx_stock_info_industry_17_code', 'jpx_stock_info', ['industry_17_code'], unique=False)
    op.create_index('jpx_stock_info_industry_33_code', 'jpx_stock_info', ['industry_33_code'], unique=False)
    op.create_index('jpx_stock_info_market_or_type', 'jpx_stock_info', ['market_or_type'], unique=False)
    op.create_index('jpx_stock_info_scale_code', 'jpx_stock_info', ['scale_code'], unique=False)
    op.create_table('stock_wiki',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('stock_wiki_code', 'stock_wiki', ['code'], unique=False)
    op.create_table('ix_head_title',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True, comment='企業名'),
    sa.Column('securities_code', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True, comment='証券コード'),
    sa.Column('document_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True, comment='書類名'),
    sa.Column('reporting_date', sa.Date(), nullable=True, comment='報告日'),
    sa.Column('current_period', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True, comment='決算期'),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True, comment='報告書種別'),
    sa.Column('listed_market', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='上場市場'),
    sa.Column('market_section', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='市場区分'),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='URL'),
    sa.Column('is_bs', sa.Boolean(), nullable=True, comment='貸借対照表'),
    sa.Column('is_pl', sa.Boolean(), nullable=True, comment='損益計算書'),
    sa.Column('is_cf', sa.Boolean(), nullable=True, comment='キャッシュフロー計算書'),
    sa.Column('is_ci', sa.Boolean(), nullable=True, comment='包括利益計算書'),
    sa.Column('is_sce', sa.Boolean(), nullable=True, comment='株主資本等変動計算書'),
    sa.Column('is_sfp', sa.Boolean(), nullable=True, comment='株主資本等変動計算書'),
    sa.Column('fy_year_end', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='決算期'),
    sa.Column('tel', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='電話番号'),
    sa.Column('is_div_rev', sa.Boolean(), nullable=True, comment='配当修正'),
    sa.Column('div_inc_rt', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='増配率'),
    sa.Column('is_fcst_rev', sa.Boolean(), nullable=True, comment='業績予想の修正'),
    sa.Column('fcst_oi_gr_rt', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='予想経常利益増益率'),
    sa.Column('oi_prog_rt', sa.Float(), nullable=True, comment='経常利益進捗率'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='有効フラグ'),
    sa.Column('is_generated', sa.Boolean(), nullable=False, comment='生成フラグ'),
    sa.Column('specific_business', sa.Boolean(), nullable=True, comment='特定事業'),
    sa.Column('is_consolidated', sa.Boolean(), nullable=True, comment='連結'),
    sa.Column('change_in_net_sales', sa.Float(), nullable=True, comment='売上高増減率'),
    sa.Column('change_in_ordinary_income', sa.Float(), nullable=True, comment='経常利益増減率'),
    sa.Column('change_in_net_income', sa.Float(), nullable=True, comment='当期純利益増減率'),
    sa.Column('change_in_fore_net_sales', sa.Float(), nullable=True, comment='予想売上高増減率'),
    sa.Column('change_in_fore_ordinary_income', sa.Float(), nullable=True, comment='予想経常利益増減率'),
    sa.Column('change_in_fore_net_income', sa.Float(), nullable=True, comment='予想純利益増減率'),
    sa.ForeignKeyConstraint(['item_key'], ['ix_file_path.head_item_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_index('idx_ix_head_specific_business', 'ix_head_title', ['specific_business'], unique=False)
    op.create_index('idx_ix_head_title_current_period', 'ix_head_title', ['current_period'], unique=False)
    op.create_index('idx_ix_head_title_is_active', 'ix_head_title', ['is_active'], unique=False)
    op.create_index('idx_ix_head_title_is_consolidated', 'ix_head_title', ['is_consolidated'], unique=False)
    op.create_index('idx_ix_head_title_is_generated', 'ix_head_title', ['is_generated'], unique=False)
    op.create_index('idx_ix_head_title_item_key', 'ix_head_title', ['item_key'], unique=False)
    op.create_index('idx_ix_head_title_report_type', 'ix_head_title', ['report_type'], unique=False)
    op.create_index('idx_ix_head_title_reporting_date', 'ix_head_title', ['reporting_date'], unique=False)
    op.create_index('idx_ix_head_title_seccode_date', 'ix_head_title', ['securities_code', 'reporting_date'], unique=False)
    op.create_table('ix_source_file',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('head_item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['head_item_key'], ['ix_head_title.item_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key'),
    sa.UniqueConstraint('source_file_id')
    )
    op.create_index('idx_ix_source_file_id', 'ix_source_file', ['source_file_id'], unique=False)
    op.create_table('ix_calculation_arc',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_arcrole', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xlink_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('head_item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('attr_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_order', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('xlink_weight', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['head_item_key'], ['ix_head_title.item_key'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.source_file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_table('ix_calculation_loc',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_schema', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('head_item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('attr_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_href', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['head_item_key'], ['ix_head_title.item_key'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.source_file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_table('ix_definition_arc',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_arcrole', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_to', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('xlink_from', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('head_item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('attr_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_order', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('xlink_weight', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['head_item_key'], ['ix_head_title.item_key'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.source_file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('head_item_key', 'source_file_id', 'xlink_from', 'xlink_to', 'xlink_arcrole', 'attr_value', name='ix_definition_arc_uc'),
    sa.UniqueConstraint('item_key')
    )
    op.create_index('idx_ix_definition_arc_attr_value', 'ix_definition_arc', ['attr_value'], unique=False)
    op.create_index('idx_ix_definition_arc_attr_value_xlink_from', 'ix_definition_arc', ['attr_value', 'xlink_from'], unique=False)
    op.create_index('idx_ix_definition_arc_attr_value_xlink_to', 'ix_definition_arc', ['attr_value', 'xlink_to'], unique=False)
    op.create_index('idx_ix_definition_arc_head_item_key', 'ix_definition_arc', ['head_item_key'], unique=False)
    op.create_index('idx_ix_definition_arc_source_file_id', 'ix_definition_arc', ['source_file_id'], unique=False)
    op.create_index('idx_ix_definition_arc_source_file_id_attr_value', 'ix_definition_arc', ['source_file_id', 'attr_value'], unique=False)
    op.create_index('idx_ix_definition_arc_xlink_arcrole', 'ix_definition_arc', ['xlink_arcrole'], unique=False)
    op.create_index('idx_ix_definition_arc_xlink_from', 'ix_definition_arc', ['xlink_from'], unique=False)
    op.create_index('idx_ix_definition_arc_xlink_order', 'ix_definition_arc', ['xlink_order'], unique=False)
    op.create_index('idx_ix_definition_arc_xlink_to', 'ix_definition_arc', ['xlink_to'], unique=False)
    op.create_table('ix_definition_loc',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_schema', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('head_item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('attr_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_href', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['head_item_key'], ['ix_head_title.item_key'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.source_file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_index('idx_ix_definition_loc_attr_value', 'ix_definition_loc', ['attr_value'], unique=False)
    op.create_index('idx_ix_definition_loc_attr_value_xlink_label', 'ix_definition_loc', ['attr_value', 'xlink_label'], unique=False)
    op.create_index('idx_ix_definition_loc_head_item_key', 'ix_definition_loc', ['head_item_key'], unique=False)
    op.create_index('idx_ix_definition_loc_source_file_id', 'ix_definition_loc', ['source_file_id'], unique=False)
    op.create_index('idx_ix_definition_loc_xlink_href', 'ix_definition_loc', ['xlink_href'], unique=False)
    op.create_index('idx_ix_definition_loc_xlink_label', 'ix_definition_loc', ['xlink_label'], unique=False)
    op.create_table('ix_label_arc',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_arcrole', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xlink_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.source_file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key'),
    sa.UniqueConstraint('xlink_arcrole', 'xlink_from', 'xlink_to', 'source_file_id', name='ix_label_arc_uc')
    )
    op.create_index('idx_ix_label_arc_source_file_id', 'ix_label_arc', ['source_file_id'], unique=False)
    op.create_index('idx_ix_label_arc_source_file_id_xlink_from', 'ix_label_arc', ['source_file_id', 'xlink_from'], unique=False)
    op.create_index('idx_ix_label_arc_source_file_id_xlink_to', 'ix_label_arc', ['source_file_id', 'xlink_to'], unique=False)
    op.create_index('idx_ix_label_arc_xlink_from', 'ix_label_arc', ['xlink_from'], unique=False)
    op.create_index('idx_ix_label_arc_xlink_to', 'ix_label_arc', ['xlink_to'], unique=False)
    op.create_table('ix_label_loc',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_schema', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_href', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xlink_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.source_file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key'),
    sa.UniqueConstraint('xlink_href', 'xlink_label', 'source_file_id', name='ix_label_loc_uc')
    )
    op.create_index('idx_ix_label_loc_source_file_id_xlink_label', 'ix_label_loc', ['source_file_id', 'xlink_label'], unique=False)
    op.create_index('idx_ix_label_loc_xlink_href', 'ix_label_loc', ['xlink_href'], unique=False)
    op.create_index('idx_ix_label_loc_xlink_label', 'ix_label_loc', ['xlink_label'], unique=False)
    op.create_table('ix_label_value',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xlink_role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xml_lang', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.source_file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key'),
    sa.UniqueConstraint('xlink_label', 'source_file_id', name='ix_label_value_uc')
    )
    op.create_index('idx_ix_label_value_source_file_id', 'ix_label_value', ['source_file_id'], unique=False)
    op.create_index('idx_ix_label_value_xlink_label', 'ix_label_value', ['xlink_label'], unique=False)
    op.create_index('idx_ix_label_value_xlink_role', 'ix_label_value', ['xlink_role'], unique=False)
    op.create_table('ix_non_fraction',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('head_item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('context', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('decimals', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scale', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('sign', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('unit_ref', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xsi_nil', sa.Boolean(), nullable=True),
    sa.Column('numeric', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('ixbrl_role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('xbrl_type', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('display_numeric', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_scale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['head_item_key'], ['ix_head_title.item_key'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.source_file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_index('idx_ix_non_fraction_context', 'ix_non_fraction', ['context'], unique=False)
    op.create_index('idx_ix_non_fraction_head_item_key', 'ix_non_fraction', ['head_item_key'], unique=False)
    op.create_index('idx_ix_non_fraction_name', 'ix_non_fraction', ['name'], unique=False)
    op.create_index('idx_ix_non_fraction_report_type', 'ix_non_fraction', ['report_type'], unique=False)
    op.create_index('idx_ix_non_fraction_xbrl_type', 'ix_non_fraction', ['xbrl_type'], unique=False)
    op.create_table('ix_non_numeric',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('head_item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('context', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('xsi_nil', sa.Boolean(), nullable=True),
    sa.Column('escape', sa.Boolean(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('ixbrl_role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('xbrl_type', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.ForeignKeyConstraint(['head_item_key'], ['ix_head_title.item_key'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.source_file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_index('idx_ix_non_numeric_context', 'ix_non_numeric', ['context'], unique=False)
    op.create_index('idx_ix_non_numeric_head_item_key', 'ix_non_numeric', ['head_item_key'], unique=False)
    op.create_index('idx_ix_non_numeric_name', 'ix_non_numeric', ['name'], unique=False)
    op.create_index('idx_ix_non_numeric_report_type', 'ix_non_numeric', ['report_type'], unique=False)
    op.create_index('idx_ix_non_numeric_xbrl_type', 'ix_non_numeric', ['xbrl_type'], unique=False)
    op.create_table('ix_presentation_arc',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_arcrole', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xlink_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('head_item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('attr_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_order', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('xlink_weight', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['head_item_key'], ['ix_head_title.item_key'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.source_file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_table('ix_presentation_loc',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_schema', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('head_item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('attr_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_href', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['head_item_key'], ['ix_head_title.item_key'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.source_file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_table('ix_qualitative',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('currentId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('parentId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('head_item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['head_item_key'], ['ix_head_title.item_key'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.source_file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currentId'),
    sa.UniqueConstraint('item_key')
    )
    op.create_index('idx_ix_qualitative_content', 'ix_qualitative', ['content'], unique=False)
    op.create_index('idx_ix_qualitative_head_item_key', 'ix_qualitative', ['head_item_key'], unique=False)
    op.create_table('ix_schema_linkbase',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True, comment='ItemKey'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('xlink_arcrole', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_href', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('xlink_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('head_item_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('xbrl_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('href_source_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.ForeignKeyConstraint(['head_item_key'], ['ix_head_title.item_key'], ),
    sa.ForeignKeyConstraint(['head_item_key'], ['ix_head_title.item_key'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['ix_source_file.source_file_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_index('idx_ix_schema_linkbase_head_item_key', 'ix_schema_linkbase', ['head_item_key'], unique=False)
    op.create_index('idx_ix_schema_linkbase_head_item_key_xlink_role', 'ix_schema_linkbase', ['head_item_key', 'xlink_role'], unique=False)
    op.create_index('idx_ix_schema_linkbase_href_source_file_id', 'ix_schema_linkbase', ['href_source_file_id'], unique=False)
    op.create_index('idx_ix_schema_linkbase_xbrl_type', 'ix_schema_linkbase', ['xbrl_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ix_schema_linkbase_xbrl_type', table_name='ix_schema_linkbase')
    op.drop_index('idx_ix_schema_linkbase_href_source_file_id', table_name='ix_schema_linkbase')
    op.drop_index('idx_ix_schema_linkbase_head_item_key_xlink_role', table_name='ix_schema_linkbase')
    op.drop_index('idx_ix_schema_linkbase_head_item_key', table_name='ix_schema_linkbase')
    op.drop_table('ix_schema_linkbase')
    op.drop_index('idx_ix_qualitative_head_item_key', table_name='ix_qualitative')
    op.drop_index('idx_ix_qualitative_content', table_name='ix_qualitative')
    op.drop_table('ix_qualitative')
    op.drop_table('ix_presentation_loc')
    op.drop_table('ix_presentation_arc')
    op.drop_index('idx_ix_non_numeric_xbrl_type', table_name='ix_non_numeric')
    op.drop_index('idx_ix_non_numeric_report_type', table_name='ix_non_numeric')
    op.drop_index('idx_ix_non_numeric_name', table_name='ix_non_numeric')
    op.drop_index('idx_ix_non_numeric_head_item_key', table_name='ix_non_numeric')
    op.drop_index('idx_ix_non_numeric_context', table_name='ix_non_numeric')
    op.drop_table('ix_non_numeric')
    op.drop_index('idx_ix_non_fraction_xbrl_type', table_name='ix_non_fraction')
    op.drop_index('idx_ix_non_fraction_report_type', table_name='ix_non_fraction')
    op.drop_index('idx_ix_non_fraction_name', table_name='ix_non_fraction')
    op.drop_index('idx_ix_non_fraction_head_item_key', table_name='ix_non_fraction')
    op.drop_index('idx_ix_non_fraction_context', table_name='ix_non_fraction')
    op.drop_table('ix_non_fraction')
    op.drop_index('idx_ix_label_value_xlink_role', table_name='ix_label_value')
    op.drop_index('idx_ix_label_value_xlink_label', table_name='ix_label_value')
    op.drop_index('idx_ix_label_value_source_file_id', table_name='ix_label_value')
    op.drop_table('ix_label_value')
    op.drop_index('idx_ix_label_loc_xlink_label', table_name='ix_label_loc')
    op.drop_index('idx_ix_label_loc_xlink_href', table_name='ix_label_loc')
    op.drop_index('idx_ix_label_loc_source_file_id_xlink_label', table_name='ix_label_loc')
    op.drop_table('ix_label_loc')
    op.drop_index('idx_ix_label_arc_xlink_to', table_name='ix_label_arc')
    op.drop_index('idx_ix_label_arc_xlink_from', table_name='ix_label_arc')
    op.drop_index('idx_ix_label_arc_source_file_id_xlink_to', table_name='ix_label_arc')
    op.drop_index('idx_ix_label_arc_source_file_id_xlink_from', table_name='ix_label_arc')
    op.drop_index('idx_ix_label_arc_source_file_id', table_name='ix_label_arc')
    op.drop_table('ix_label_arc')
    op.drop_index('idx_ix_definition_loc_xlink_label', table_name='ix_definition_loc')
    op.drop_index('idx_ix_definition_loc_xlink_href', table_name='ix_definition_loc')
    op.drop_index('idx_ix_definition_loc_source_file_id', table_name='ix_definition_loc')
    op.drop_index('idx_ix_definition_loc_head_item_key', table_name='ix_definition_loc')
    op.drop_index('idx_ix_definition_loc_attr_value_xlink_label', table_name='ix_definition_loc')
    op.drop_index('idx_ix_definition_loc_attr_value', table_name='ix_definition_loc')
    op.drop_table('ix_definition_loc')
    op.drop_index('idx_ix_definition_arc_xlink_to', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_xlink_order', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_xlink_from', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_xlink_arcrole', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_source_file_id_attr_value', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_source_file_id', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_head_item_key', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_attr_value_xlink_to', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_attr_value_xlink_from', table_name='ix_definition_arc')
    op.drop_index('idx_ix_definition_arc_attr_value', table_name='ix_definition_arc')
    op.drop_table('ix_definition_arc')
    op.drop_table('ix_calculation_loc')
    op.drop_table('ix_calculation_arc')
    op.drop_index('idx_ix_source_file_id', table_name='ix_source_file')
    op.drop_table('ix_source_file')
    op.drop_index('idx_ix_head_title_seccode_date', table_name='ix_head_title')
    op.drop_index('idx_ix_head_title_reporting_date', table_name='ix_head_title')
    op.drop_index('idx_ix_head_title_report_type', table_name='ix_head_title')
    op.drop_index('idx_ix_head_title_item_key', table_name='ix_head_title')
    op.drop_index('idx_ix_head_title_is_generated', table_name='ix_head_title')
    op.drop_index('idx_ix_head_title_is_consolidated', table_name='ix_head_title')
    op.drop_index('idx_ix_head_title_is_active', table_name='ix_head_title')
    op.drop_index('idx_ix_head_title_current_period', table_name='ix_head_title')
    op.drop_index('idx_ix_head_specific_business', table_name='ix_head_title')
    op.drop_table('ix_head_title')
    op.drop_index('stock_wiki_code', table_name='stock_wiki')
    op.drop_table('stock_wiki')
    op.drop_index('jpx_stock_info_scale_code', table_name='jpx_stock_info')
    op.drop_index('jpx_stock_info_market_or_type', table_name='jpx_stock_info')
    op.drop_index('jpx_stock_info_industry_33_code', table_name='jpx_stock_info')
    op.drop_index('jpx_stock_info_industry_17_code', table_name='jpx_stock_info')
    op.drop_table('jpx_stock_info')
    op.drop_table('ix_file_path')
    # ### end Alembic commands ###
