"""stock_wiki table add by kent

Revision ID: d5847526e014
Revises: ea34744a18de
Create Date: 2025-02-13 22:28:04.250603

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd5847526e014'
down_revision = 'ea34744a18de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_wiki',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('stock_wiki_code', 'stock_wiki', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('stock_wiki_code', table_name='stock_wiki')
    op.drop_table('stock_wiki')
    # ### end Alembic commands ###
