"""stock_wiki table url add None by kent

Revision ID: d7bc55f2341a
Revises: 54d4c2533224
Create Date: 2025-02-14 21:23:11.094645

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d7bc55f2341a"
down_revision = "54d4c2533224"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_wiki", "url", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_wiki", "url", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
