"""add index

Revision ID: e4547e321d6c
Revises: 16a9353c24ee
Create Date: 2024-11-25 20:20:33.562662

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e4547e321d6c'
down_revision = '16a9353c24ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ix_head_title_current_period', 'ix_head_title', ['current_period'], unique=False)
    op.create_index('idx_ix_non_fraction_report_type', 'ix_non_fraction', ['report_type'], unique=False)
    op.create_index('idx_ix_non_numeric_report_type', 'ix_non_numeric', ['report_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ix_non_numeric_report_type', table_name='ix_non_numeric')
    op.drop_index('idx_ix_non_fraction_report_type', table_name='ix_non_fraction')
    op.drop_index('idx_ix_head_title_current_period', table_name='ix_head_title')
    # ### end Alembic commands ###
