"""Create StocInfoTable

Revision ID: ea17349247ae
Revises: 92d6a24acc5a
Create Date: 2025-01-29 05:20:04.453688

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ea17349247ae'
down_revision = '92d6a24acc5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('insert_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('market_or_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('industry_33_code', sa.Integer(), nullable=True),
    sa.Column('industry_33_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('industry_17_code', sa.Integer(), nullable=True),
    sa.Column('industry_17_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('scale_code', sa.Integer(), nullable=True),
    sa.Column('scale_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_info')
    # ### end Alembic commands ###
