"""Change IcHeadTitleSummary Add Fields

Revision ID: eb0d32942ba9
Revises: 3fe45e8766dd
Create Date: 2025-06-14 11:19:30.642695

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eb0d32942ba9'
down_revision = '3fe45e8766dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ix_head_title_summary', sa.Column('operating_result_json', sa.Text(), nullable=True))
    op.add_column('ix_head_title_summary', sa.Column('forecast_json', sa.Text(), nullable=True))
    op.add_column('ix_head_title_summary', sa.Column('cashflow_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ix_head_title_summary', 'cashflow_json')
    op.drop_column('ix_head_title_summary', 'forecast_json')
    op.drop_column('ix_head_title_summary', 'operating_result_json')
    # ### end Alembic commands ###
