"""Rename JpxStockInfo table

Revision ID: f99da43d202e
Revises: b40af2713e41
Create Date: 2025-01-29 05:48:32.485774

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f99da43d202e'
down_revision = 'b40af2713e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
