/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutSummaryIndexImport } from './routes/_layout/summary/index'
import { Route as LayoutSummaryHeaditemkeyImport } from './routes/_layout/summary/$head_item_key'
import { Route as LayoutMenuSelectedDateImport } from './routes/_layout/menu.$selectedDate'
import { Route as LayoutSummaryHeaditemkeyIndexImport } from './routes/_layout/summary/$head_item_key/index'
import { Route as LayoutSummaryHeaditemkeyRvfcImport } from './routes/_layout/summary/$head_item_key/rvfc'
import { Route as LayoutSummaryHeaditemkeyRvdfImport } from './routes/_layout/summary/$head_item_key/rvdf'
import { Route as LayoutSummaryHeaditemkeyRrfcImport } from './routes/_layout/summary/$head_item_key/rrfc'
import { Route as LayoutSummaryHeaditemkeyRrdfImport } from './routes/_layout/summary/$head_item_key/rrdf'
import { Route as LayoutSummaryHeaditemkeyRejpImport } from './routes/_layout/summary/$head_item_key/rejp'
import { Route as LayoutSummaryHeaditemkeyEfjpImport } from './routes/_layout/summary/$head_item_key/efjp'
import { Route as LayoutSummaryHeaditemkeyEdusImport } from './routes/_layout/summary/$head_item_key/edus'
import { Route as LayoutSummaryHeaditemkeyEdjpImport } from './routes/_layout/summary/$head_item_key/edjp'
import { Route as LayoutSummaryHeaditemkeyEditImport } from './routes/_layout/summary/$head_item_key/edit'
import { Route as LayoutSummaryHeaditemkeyEdifImport } from './routes/_layout/summary/$head_item_key/edif'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSummaryIndexRoute = LayoutSummaryIndexImport.update({
  path: '/summary/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSummaryHeaditemkeyRoute = LayoutSummaryHeaditemkeyImport.update({
  path: '/summary/$head_item_key',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMenuSelectedDateRoute = LayoutMenuSelectedDateImport.update({
  path: '/menu/$selectedDate',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSummaryHeaditemkeyIndexRoute =
  LayoutSummaryHeaditemkeyIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutSummaryHeaditemkeyRoute,
  } as any)

const LayoutSummaryHeaditemkeyRvfcRoute =
  LayoutSummaryHeaditemkeyRvfcImport.update({
    path: '/rvfc',
    getParentRoute: () => LayoutSummaryHeaditemkeyRoute,
  } as any)

const LayoutSummaryHeaditemkeyRvdfRoute =
  LayoutSummaryHeaditemkeyRvdfImport.update({
    path: '/rvdf',
    getParentRoute: () => LayoutSummaryHeaditemkeyRoute,
  } as any)

const LayoutSummaryHeaditemkeyRrfcRoute =
  LayoutSummaryHeaditemkeyRrfcImport.update({
    path: '/rrfc',
    getParentRoute: () => LayoutSummaryHeaditemkeyRoute,
  } as any)

const LayoutSummaryHeaditemkeyRrdfRoute =
  LayoutSummaryHeaditemkeyRrdfImport.update({
    path: '/rrdf',
    getParentRoute: () => LayoutSummaryHeaditemkeyRoute,
  } as any)

const LayoutSummaryHeaditemkeyRejpRoute =
  LayoutSummaryHeaditemkeyRejpImport.update({
    path: '/rejp',
    getParentRoute: () => LayoutSummaryHeaditemkeyRoute,
  } as any)

const LayoutSummaryHeaditemkeyEfjpRoute =
  LayoutSummaryHeaditemkeyEfjpImport.update({
    path: '/efjp',
    getParentRoute: () => LayoutSummaryHeaditemkeyRoute,
  } as any)

const LayoutSummaryHeaditemkeyEdusRoute =
  LayoutSummaryHeaditemkeyEdusImport.update({
    path: '/edus',
    getParentRoute: () => LayoutSummaryHeaditemkeyRoute,
  } as any)

const LayoutSummaryHeaditemkeyEdjpRoute =
  LayoutSummaryHeaditemkeyEdjpImport.update({
    path: '/edjp',
    getParentRoute: () => LayoutSummaryHeaditemkeyRoute,
  } as any)

const LayoutSummaryHeaditemkeyEditRoute =
  LayoutSummaryHeaditemkeyEditImport.update({
    path: '/edit',
    getParentRoute: () => LayoutSummaryHeaditemkeyRoute,
  } as any)

const LayoutSummaryHeaditemkeyEdifRoute =
  LayoutSummaryHeaditemkeyEdifImport.update({
    path: '/edif',
    getParentRoute: () => LayoutSummaryHeaditemkeyRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/menu/$selectedDate': {
      preLoaderRoute: typeof LayoutMenuSelectedDateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/summary/$head_item_key': {
      preLoaderRoute: typeof LayoutSummaryHeaditemkeyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/summary/': {
      preLoaderRoute: typeof LayoutSummaryIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/summary/$head_item_key/edif': {
      preLoaderRoute: typeof LayoutSummaryHeaditemkeyEdifImport
      parentRoute: typeof LayoutSummaryHeaditemkeyImport
    }
    '/_layout/summary/$head_item_key/edit': {
      preLoaderRoute: typeof LayoutSummaryHeaditemkeyEditImport
      parentRoute: typeof LayoutSummaryHeaditemkeyImport
    }
    '/_layout/summary/$head_item_key/edjp': {
      preLoaderRoute: typeof LayoutSummaryHeaditemkeyEdjpImport
      parentRoute: typeof LayoutSummaryHeaditemkeyImport
    }
    '/_layout/summary/$head_item_key/edus': {
      preLoaderRoute: typeof LayoutSummaryHeaditemkeyEdusImport
      parentRoute: typeof LayoutSummaryHeaditemkeyImport
    }
    '/_layout/summary/$head_item_key/efjp': {
      preLoaderRoute: typeof LayoutSummaryHeaditemkeyEfjpImport
      parentRoute: typeof LayoutSummaryHeaditemkeyImport
    }
    '/_layout/summary/$head_item_key/rejp': {
      preLoaderRoute: typeof LayoutSummaryHeaditemkeyRejpImport
      parentRoute: typeof LayoutSummaryHeaditemkeyImport
    }
    '/_layout/summary/$head_item_key/rrdf': {
      preLoaderRoute: typeof LayoutSummaryHeaditemkeyRrdfImport
      parentRoute: typeof LayoutSummaryHeaditemkeyImport
    }
    '/_layout/summary/$head_item_key/rrfc': {
      preLoaderRoute: typeof LayoutSummaryHeaditemkeyRrfcImport
      parentRoute: typeof LayoutSummaryHeaditemkeyImport
    }
    '/_layout/summary/$head_item_key/rvdf': {
      preLoaderRoute: typeof LayoutSummaryHeaditemkeyRvdfImport
      parentRoute: typeof LayoutSummaryHeaditemkeyImport
    }
    '/_layout/summary/$head_item_key/rvfc': {
      preLoaderRoute: typeof LayoutSummaryHeaditemkeyRvfcImport
      parentRoute: typeof LayoutSummaryHeaditemkeyImport
    }
    '/_layout/summary/$head_item_key/': {
      preLoaderRoute: typeof LayoutSummaryHeaditemkeyIndexImport
      parentRoute: typeof LayoutSummaryHeaditemkeyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutItemsRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
    LayoutMenuSelectedDateRoute,
    LayoutSummaryHeaditemkeyRoute.addChildren([
      LayoutSummaryHeaditemkeyEdifRoute,
      LayoutSummaryHeaditemkeyEditRoute,
      LayoutSummaryHeaditemkeyEdjpRoute,
      LayoutSummaryHeaditemkeyEdusRoute,
      LayoutSummaryHeaditemkeyEfjpRoute,
      LayoutSummaryHeaditemkeyRejpRoute,
      LayoutSummaryHeaditemkeyRrdfRoute,
      LayoutSummaryHeaditemkeyRrfcRoute,
      LayoutSummaryHeaditemkeyRvdfRoute,
      LayoutSummaryHeaditemkeyRvfcRoute,
      LayoutSummaryHeaditemkeyIndexRoute,
    ]),
    LayoutSummaryIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
