/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutTimelineImport } from './routes/_layout/timeline'
import { Route as LayoutCategoryImport } from './routes/_layout/category'
import { Route as LayoutTimelineIndustry33Industry33Import } from './routes/_layout/timeline/industry33.$industry_33'
import { Route as LayoutTimelineIndustry17Industry17Import } from './routes/_layout/timeline/industry17.$industry_17'
import { Route as LayoutTimelineDateDateStrImport } from './routes/_layout/timeline/date.$dateStr'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTimelineRoute = LayoutTimelineImport.update({
  path: '/timeline',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCategoryRoute = LayoutCategoryImport.update({
  path: '/category',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTimelineIndustry33Industry33Route =
  LayoutTimelineIndustry33Industry33Import.update({
    path: '/industry33/$industry_33',
    getParentRoute: () => LayoutTimelineRoute,
  } as any)

const LayoutTimelineIndustry17Industry17Route =
  LayoutTimelineIndustry17Industry17Import.update({
    path: '/industry17/$industry_17',
    getParentRoute: () => LayoutTimelineRoute,
  } as any)

const LayoutTimelineDateDateStrRoute = LayoutTimelineDateDateStrImport.update({
  path: '/date/$dateStr',
  getParentRoute: () => LayoutTimelineRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/category': {
      preLoaderRoute: typeof LayoutCategoryImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/timeline': {
      preLoaderRoute: typeof LayoutTimelineImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/timeline/date/$dateStr': {
      preLoaderRoute: typeof LayoutTimelineDateDateStrImport
      parentRoute: typeof LayoutTimelineImport
    }
    '/_layout/timeline/industry17/$industry_17': {
      preLoaderRoute: typeof LayoutTimelineIndustry17Industry17Import
      parentRoute: typeof LayoutTimelineImport
    }
    '/_layout/timeline/industry33/$industry_33': {
      preLoaderRoute: typeof LayoutTimelineIndustry33Industry33Import
      parentRoute: typeof LayoutTimelineImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutCategoryRoute,
    LayoutTimelineRoute.addChildren([
      LayoutTimelineDateDateStrRoute,
      LayoutTimelineIndustry17Industry17Route,
      LayoutTimelineIndustry33Industry33Route,
    ]),
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
